<?php

namespace RemindCloud\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Client
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Client extends EntityRepository
{
}
