<?php

namespace RemindCloud\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Newsletter
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Newsletter extends EntityRepository
{

    public function findById($id)
    {
        $query = $this->_em->createQuery("
            SELECT
                m.id,
                m.companyid,
                m.subject,
                m.body,
                m.sendDate,
                m.sent,
                m.published
            FROM RemindCloud\Entity\Newsletter m
            WHERE m.id = ?1
        ");
        return $query->execute(array(1 => $id));
    }
}
